services:
  - type: web
    name: treasure-home-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
