services:
  - type: web
    name: treasure-home-school-server
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: your_database_url_here
      - key: SESSION_SECRET
        generateValue: true
